/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hduofjzsitoaujyjvuix"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkdW9manpzaXRvYXVqeWp2dWl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwNDIzNjcsImV4cCI6MjA3NzYxODM2N30.NO-8BQoTAJS3LtXE_Bqb_F4lmLbRB9-cLcMUUjzh1gY"